// biome-ignore-all format: generated
// This file is auto-generated by kitcn migrate create.
// Do not edit manually.

import { defineMigrationSet } from 'kitcn/orm';
import { migration as migration_0 } from './20260906_022807_backfill_project_access';

export const migrations = defineMigrationSet([
  migration_0,
]);
